### ISSUE TITLE
Cannot find module “aws-amplify”

### ISSUE THREAD

**Issue by officeguy** [grimbonious/ember-cli-amplify#3]
Hi,
When implementing this addon as per https://itnext.io/adding-aws-amplify-to-an-ember-js-application-72683167c476 I am getting the symptom of:

-ember-cli-webpack-imports-bundle.js:70 Uncaught Error: Cannot find module “aws-amplify”

this was working fine in october so perhaps a regression has occurred.

my current versions are:

ember-cli: 3.5.1
node: 10.10.0
os: darwin x64
amplify: 0.1.35
ember-cli-amplify 0.3.0

**Comment by rangana** [comment]
I'm also getting the same issue with the approach mentioned in the article, Any resolution? 


> Uncaught Error: Cannot find module "aws-amplify"
>     at webpackMissingModule (-ember-cli-webpack-imports-bundle.js:70)
>     at Object.<anonymous> (-ember-cli-webpack-imports-bundle.js:70)
>     at __webpack_require__ (-ember-cli-webpack-imports-bundle.js:20)
>     at -ember-cli-webpack-imports-bundle.js:63
>     at Module.callback (-ember-cli-webpack-imports-bundle.js:66)
>     at Module.exports (loader.js:106)
>     at Module._reify (loader.js:143)
>     at Module.reify (loader.js:130)
>     at Module.exports (loader.js:104)
>     at Module._reify (loader.js:143)

**Comment by mayankbpatel** [comment]
I have the same problem on a brand new ember app.  Appreciate any workarounds people have found.  Thanks.

**Comment by officeguy** [comment]
fyi I had hoped that this would help, but my testing of it hasn't resolved the symptom :(
https://github.com/ef4/ember-auto-import

**Comment by sohara** [comment]
@officeguy I'm not using this addon (just manually copied the service and initializer to my app) but I am using `aws-amplify` and and `ember-auto-import` in my ember app. I ran into the same error but it went away when I moved `aws-amplify` from my `devDependencies` to `dependencies` in my package.json.

**Comment by officeguy** [comment]
excellent, I've tried that and it worked. thanks @sohara
